#!/bin/bash

# Copyright (C) 2024-2025 Intel Corporation
#
# SPDX-License-Identifier: MIT

set -e -o pipefail

if lsmod | grep intel_vpu > /dev/null && [ -e "$(modinfo -n intel_vpu 2> /dev/null)" ]; then
    rmmod intel_vpu
    modprobe intel_vpu
fi
